WIP: user-admin
wolox-training/gd-node-ts pull request #10
Opened 2022-09-01 15:21 UTC by gastonmd14

## Summary

[Change!] Describe your feature, problems you had, notes, improvements and others.

## Known Issues

[Change!] List any known issue of the feature you are implementing.

## Trello Card

[Change!] Link to the associated Trello card.

2022-09-14 13:28 UTC, elcorren commented on app/routes.ts
> +import { getUsers, getUserById, getUserByEmail, createUser, adminUser } from './controllers/users';
Para evitar tener varias líneas importando controladores, podrías crear el archivo *controllers/index.ts* y dentro de este exportar todos los controladores, teniendo una línea por cada archivo. Por ejemplo:
```
export * from './users'
export * from '......
```
Luego desde el archivo de rutas simplemente importas todos los controladores que necesites, algo así:
```
import { healthCheck , getUsers, getHScards, ....... } from './controllers';
```

2022-09-14 14:20 UTC, elcorren requested changes

2022-09-14 14:20 UTC, elcorren commented on app/services/users.ts
> +    aux.password = bcrypt.hashSync(aux.password, 10);
Que funcionalidad tiene *aux* ? veo que no la utilizás más que para hashear su propiedad *password* 🤔

2022-09-14 14:20 UTC, elcorren commented on migrations/migrations/1661974044597-add-admin-user.ts
> +      'INSERT INTO "User" ("username", "lastname", "email", "password", "role") VALUES (\'john\', \'dow\', \'john.dow@wolox.com\', \'$2a$10$b/1J8bfFdv7ib/8XWhScaePV1.OfbfbstW00ynbOPk3WloCifVtJC\', \'
Por qué añadís este user por migración? 🤔 🐛

2022-09-14 14:20 UTC, elcorren commented on tests/admin.spec.ts
> +          'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJqb2huIiwibGFzdG5hbWUiOiJkb3ciLCJlbWFpbCI6ImpvaG4uZG93QHdvbG94LmNvbSIsInJvbGUiOiJhZG1pbiJ9.MWeUu0OO-bkB0ByLjMXRYiJH5fQ
estos paramámetros podrías meterlos en un archivo de config, así no lo hardcodeas y no lo repetís en el código

2022-09-14 14:20 UTC, elcorren commented on tests/admin.spec.ts
> +      {
Podrías definir los distintos objetos dentro de un archivo de constantes y los importas en los tests, así queda más legible el código 👍

2022-09-29 15:21 UTC, gastonmd14 commented on app/routes.ts
> +import { getUsers, getUserById, getUserByEmail, createUser, adminUser } from './controllers/users';
Ya quedo solucionado

2022-09-29 15:22 UTC, gastonmd14 commented on app/services/users.ts
> +    aux.password = bcrypt.hashSync(aux.password, 10);
Ya quedo solucionado

2022-09-29 15:24 UTC, gastonmd14 commented on migrations/migrations/1661974044597-add-admin-user.ts
> +      'INSERT INTO "User" ("username", "lastname", "email", "password", "role") VALUES (\'john\', \'dow\', \'john.dow@wolox.com\', \'$2a$10$b/1J8bfFdv7ib/8XWhScaePV1.OfbfbstW00ynbOPk3WloCifVtJC\', \'
Necesito tener un usuario admin para poder generar un token para el endpoint de /admin/users ya que debe estar autenticado previamente.

2022-09-29 15:41 UTC, gastonmd14 commented on tests/admin.spec.ts
> +          'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJqb2huIiwibGFzdG5hbWUiOiJkb3ciLCJlbWFpbCI6ImpvaG4uZG93QHdvbG94LmNvbSIsInJvbGUiOiJhZG1pbiJ9.MWeUu0OO-bkB0ByLjMXRYiJH5fQ
Ya quedo solucionado

2022-09-29 15:41 UTC, gastonmd14 commented on tests/admin.spec.ts
> +      {
Ya quedo solucionado

2022-09-29 17:59 UTC, elcorren commented on app/routes.ts
> +import usersMiddlewares from './middlewares/users';
los controladores podrías importarlos desde la misma línea, a partir de que los exportas desde un index.ts la cada carpeta. Lo mismo con los middlewares

2022-09-29 18:12 UTC, elcorren approved these changes

2022-09-29 18:19 UTC, merged