wip: buy-card
wolox-training/gd-node-ts pull request #12
Opened 2022-09-09 22:19 UTC by gastonmd14

## Summary

Add buy card endpoint with test

## Known Issues

None

## Trello Card

https://trello.com/c/nKt3L8N8/35-comprar-carta

2022-09-29 19:51 UTC, elcorren requested changes

2022-09-29 19:51 UTC, elcorren commented on app/controllers/hearthstone.ts
> +  await findUser(user).then(async (userFounded: User) => {
Para evitar usar muchos .then anidados podrías reemplazarlos por async/await. Te quedará el código más legible y evitarías caer en el callback hell 🔥

2022-09-29 19:51 UTC, elcorren commented on app/middlewares/users.ts
> +      return res.status(400).json({ message: 'Permmission is not allowed' });
un usuario puede tener otro rol además de standar y admin? 🤔

2022-09-29 19:51 UTC, elcorren commented on app/middlewares/users.ts
> +      if (user.role === 'admin') {
ya que tenés el registro user desde DB, es más confiable consultar el rol desde este y no desde el user que trae el token

2022-10-12 16:48 UTC, gastonmd14 commented on app/controllers/hearthstone.ts
> +  await findUser(user).then(async (userFounded: User) => {
Listu

2022-10-12 16:48 UTC, gastonmd14 commented on app/middlewares/users.ts
> +      if (user.role === 'admin') {
se cambio el comportamiento.

2022-11-01 17:42 UTC, elcorren requested changes

2022-11-01 17:42 UTC, elcorren commented on app/middlewares/users.ts
> +      if (user.role === 'admin') {
revisar

2022-11-01 17:42 UTC, elcorren commented on app/middlewares/users.ts
> +      if (user.role) {
En qué caso no la propiedad role no estaría definida?

2022-11-01 17:42 UTC, elcorren commented on app/controllers/hearthstone.ts
> +    } else if (userToFind) {
Qué sucede si `userToFind = undefined` ?

2022-11-01 20:47 UTC, gastonmd14 commented on app/middlewares/users.ts
> +      if (user.role) {
Debido a que la propiedad siempre esta definida de modifico el codigo.

2022-11-01 20:47 UTC, gastonmd14 commented on app/controllers/hearthstone.ts
> +    } else if (userToFind) {
se modifico el codigo para el caso de undefined

2022-11-02 18:02 UTC, elcorren requested changes

2022-11-02 18:02 UTC, elcorren commented on app/controllers/hearthstone.ts
> +export async function createHScard(
Quizás modificando las condiciones de los IFs quedaría más legible el código. Fijate qué te parece una cosa así, chequeando las condiciones contrarias
```
export async function createHScard(
  req: Request,
  res: Response,
  next: NextFunction
): Promise<Response | NextFunction> {
  const { path, params } = req;
  const { user } = req.body;
  const method = 'GET';
  try {
    const userToFind = await findUser(user);
    if (!userToFind) {
      logger.error(HTTP_CODES.NOT_FOUND);
      return res.status(HttpStatus.NOT_FOUND).send(HTTP_CODES.NOT_FOUND);
    }
    const cardByUser = userToFind?.cards.find((card: Card) => card.cardId === params.id);
    if (cardByUser) {
      logger.error(HTTP_CODES.CONFLICT);
      return res.status(HttpStatus.CONFLICT).send({ message: 'DUPLICATE CARD' });
    }
    const card = await createCard(userToFind, path, method);
    if (!card) {
      logger.error(HTTP_CODES.BAD_REQUEST);
      return res.status(HttpStatus.BAD_REQUEST).send(HTTP_CODES.BAD_REQUEST);
    }
    logger.info(HTTP_CODES.CREATED);
    return res.status(HttpStatus.CREATED).send(successful.CREATED);
  } catch (err) {
    logger.error({ error: err, message: HTTP_CODES.INTERNAL_SERVER_ERROR });
    return next;
  }
}
```

2022-11-02 18:02 UTC, elcorren commented on app/middlewares/users.ts
> +export async function isStandardOrAdmin(
Por el comportamiento de la función quizás sea mejor renombrarla a "userExists" o similar. Qué te parece?

2022-11-02 18:02 UTC, elcorren commented on app/middlewares/users.ts
> +    if (userToFind) {
Para evitar los condicionales anidados podrías modificar las condiciones para chequear los casos negativos:
```
    if (!userToFind) {
      return res.status(404).json({ message: 'User not found' });
    }
    if (userToFind.role !== 'admin') {
      return res.status(400).json({ message: 'Permmission is not allowed' });
    }
    return next();
```

2022-11-17 20:07 UTC, gastonmd14 commented on app/controllers/hearthstone.ts
> +export async function createHScard(
Se actualizo el codigo para evitar los if anidados

2022-11-17 20:07 UTC, gastonmd14 commented on app/middlewares/users.ts
> +export async function isStandardOrAdmin(
Se cambio la variable a userExits

2022-11-17 20:08 UTC, gastonmd14 commented on app/middlewares/users.ts
> +    if (userToFind) {
Se actualizo el codigo para evitar los if anidados

2022-11-24 19:45 UTC, elcorren approved these changes

2022-11-24 20:00 UTC, merged