WIP: create-set
wolox-training/gd-node-ts pull request #13
Opened 2022-10-12 16:55 UTC by gastonmd14

## Summary

Add Set model

## Known Issues

None

## Trello Card

https://trello.com/c/X7fIeUVp/36-crear-una-baraja

2022-11-25 18:43 UTC, elcorren commented on app/controllers/sets.ts
> +      user: user
como la key y el value poseen el mismo nombre, solamente haciendo referencia a la variable ya funciona
```
const set = {
  name: setName,
  user
}
```

2022-11-25 18:44 UTC, elcorren commented on app/middlewares/users.ts
> +  if (!req.headers.authorization) return res.status(400).json(error.TOKEN_REQUIRED);
Fijate de cambiar los codes por tus constantes para el próximo PR 💡

2022-11-25 18:45 UTC, elcorren commented on app/middlewares/users.ts
> +  if (!userToFind) return res.status(404).json(error.NOT_FOUND_USER);
idem

2022-11-25 18:45 UTC, elcorren commented on app/middlewares/users.ts
> +  if (!req.headers.authorization) return res.status(400).json(error.TOKEN_REQUIRED);
idem

2022-11-25 18:45 UTC, elcorren commented on app/middlewares/users.ts
> +  if (!userToFind) return res.status(404).json(error.NOT_FOUND_USER);
idem

2022-11-25 18:45 UTC, elcorren commented on app/middlewares/users.ts
> +  return res.status(400).json(error.PERMMISSION_NOT_ALLOW);
same

2022-11-25 19:19 UTC, elcorren requested changes

2022-11-25 19:19 UTC, elcorren commented on app/services/sets.ts
> +const params = (apiPath: string, apiMethod: string): object =>
Podés utilizar los types e interfaces de Axios para el tipado de tus funciones:
```
const params = (apiPath: string, apiMethod: Method): AxiosRequestConfig => ({
  method: apiMethod,
  url: apiPath,
  baseURL: process.env.API_HS_URL,
  headers: {
    'X-RapidAPI-Key': process.env.API_HS_KEY,
    'X-RapidAPI-Host': process.env.API_HS_HOST
  }
});
```
El type `Method` te permite utilizar cualquiera de estos inputs
```
export type Method =
  | 'get' | 'GET'
  | 'delete' | 'DELETE'
  | 'head' | 'HEAD'
  | 'options' | 'OPTIONS'
  | 'post' | 'POST'
  | 'put' | 'PUT'
  | 'patch' | 'PATCH'
  | 'link' | 'LINK'
  | 'unlink' | 'UNLINK'
```
De esta manera te queda más robusta tu función y no haces el casteo mediante `as` que evade el type check de Typescript

2022-11-25 19:19 UTC, elcorren commented on app/services/sets.ts
> +export const getSetInfo = async (apiPath: string, apiMethod: string): Promise<Info> => {
En este caso también podés utilizar el type `Method`

2022-12-01 22:33 UTC, gastonmd14 commented on app/controllers/sets.ts
> +      user: user
Se cambio la variable.

2022-12-01 22:33 UTC, gastonmd14 commented on app/middlewares/users.ts
> +  if (!req.headers.authorization) return res.status(400).json(error.TOKEN_REQUIRED);
Se actualizo el code.

2022-12-01 22:33 UTC, gastonmd14 commented on app/middlewares/users.ts
> +  if (!userToFind) return res.status(404).json(error.NOT_FOUND_USER);
Se actualizo el code.

2022-12-01 22:33 UTC, gastonmd14 commented on app/middlewares/users.ts
> +  if (!userToFind) return res.status(404).json(error.NOT_FOUND_USER);
Se actualizo el code.

2022-12-01 22:34 UTC, gastonmd14 commented on app/middlewares/users.ts
> +  return res.status(400).json(error.PERMMISSION_NOT_ALLOW);
Se actualizo el code.

2022-12-01 22:34 UTC, gastonmd14 commented on app/services/sets.ts
> +const params = (apiPath: string, apiMethod: string): object =>
Se utilizo method de Axios.

2022-12-01 22:34 UTC, gastonmd14 commented on app/services/sets.ts
> +export const getSetInfo = async (apiPath: string, apiMethod: string): Promise<Info> => {
Se utilizo method de Axios.

2022-12-01 22:34 UTC, gastonmd14 commented on app/middlewares/users.ts
> +  if (!req.headers.authorization) return res.status(400).json(error.TOKEN_REQUIRED);
Se actualizo el code.

2022-12-01 22:36 UTC, merged